language: ruby
rvm:
  - 2.3.1
services:
  - memcached
before_script:
  - cat hdconfig.yml | sed -e s/your_api_username/$API_USERNAME/ -e s/your_api_secret/$API_SECRET/ -e s/your_api_siteId/$API_SITE_ID/ > hd4_ci_config.yml
